#!/bin/bash

ISUCS="$(hostname |grep ucs -c)"

if [ $ISUCS -ne 0 ]; then
	echo "Do not run this on ucs host. Exiting..."
	exit 1
fi

apt-get update
apt-get -y --purge autoremove
apt-get -y autoclean
apt-get -y upgrade
apt-get -y dist-upgrade
apt -y install htop glances dstat ladvd snmpd ntp tcpdump autofs logwatch molly-guard

slack tsys-base-$tsysSysLocation
